services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --protocol quic --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - web
    restart: unless-stopped
